stages:
  - build
  - deploy
  - cleanup

build:
  stage: build
  script:
    - |
    IMAGE_VERSION=
    ./scripts/build.sh --image ${IMAGE_NAME} \
                       --version ${IMAGE_VERSION}
  when:

deploy:
  stage: deploy
  script:
    - |
    IMAGE_VERSION=$(echo )
    ./scripts/deploy.sh --image ${IMAGE_NAME} \ 
                        --version ${IMAGE_VERSION} \
                        --registry ${CONTAINER_REGISTRY} \
                        --registry-username ${CONTAINER_REGISTRY_USERNAME} \
                        --registry-password ${CONTAINER_REGISTRY_PASSWORD}
  when:

cleanup:
  stage: cleanup
  script:
    - |
    IMAGE_VERSION=
    ./scripts/cleanup.sh --image ${IMAGE_NAME} \
                         --version ${IMAGE_VERSION}
  when:
